<a href="https://colab.research.google.com/github/Raghad-Waleed/retail-sales-insights/blob/main/model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
file_path = '/content/drive/MyDrive/Final_Project_Data/Superstore Sales Dataset.csv'

# Data processing

In [ ]:
import pandas as pd

#Read data

df = pd.read_csv(file_path)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [ ]:
#import pandas as pd

#Read data

#df = pd.read_csv('Superstore Sales Dataset.csv')

# 1. Top Inshights

Top 10 customers by sales

In [ ]:
top_10_customers = df.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False).head(10)
top_10_customers

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

top product by sales

In [ ]:
top_products = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(1)
(top_products)

Product Name
Canon imageCLASS 2200 Advanced Copier    61599.824
Name: Sales, dtype: float64

sort subcategory by sales From largest to least

In [ ]:
sort_subcategory = df.groupby('Sub-Category')['Sales'].sum().sort_values(ascending=False)
sort_subcategory

Sub-Category
Phones         327782.4480
Chairs         322822.7310
Storage        219343.3920
Tables         202810.6280
Binders        200028.7850
Machines       189238.6310
Accessories    164186.7000
Copiers        146248.0940
Bookcases      113813.1987
Appliances     104618.4030
Furnishings     89212.0180
Paper           76828.3040
Supplies        46420.3080
Art             26705.4100
Envelopes       16128.0460
Labels          12347.7260
Fasteners        3001.9600
Name: Sales, dtype: float64

# 2. Geographical Analysis

Sales by state

In [ ]:

sales_by_state = df.groupby('State')['Sales'].sum().sort_values(ascending=False)
sales_by_state

State
California              446306.4635
New York                306361.1470
Texas                   168572.5322
Washington              135206.8500
Pennsylvania            116276.6500
Florida                  88436.5320
Illinois                 79236.5170
Michigan                 76136.0740
Ohio                     75130.3500
Virginia                 70636.7200
North Carolina           55165.9640
Indiana                  48718.4000
Georgia                  48219.1100
Kentucky                 36458.3900
Arizona                  35272.6570
New Jersey               34610.9720
Colorado                 31841.5980
Wisconsin                31173.4300
Tennessee                30661.8730
Minnesota                29863.1500
Massachusetts            28634.4340
Delaware                 27322.9990
Maryland                 23705.5230
Rhode Island             22525.0260
Missouri                 22205.1500
Oklahoma                 19683.3900
Alabama                  19510.6400
Oregon                   17284.4620
Nevada                   16729.1020
Connecticut              13384.3570
Arkansas                 11678.1300
Utah                     11220.0560
Mississippi              10771.3400
Louisiana                 9131.0500
Vermont                   8929.3700
South Carolina            8481.7100
Nebraska                  7464.9300
New Hampshire             7292.5240
Montana                   5589.3520
New Mexico                4783.5220
Iowa                      4443.5600
Idaho                     4382.4860
Kansas                    2914.3100
District of Columbia      2865.0200
Wyoming                   1603.1360
South Dakota              1315.5600
Maine                     1270.5300
West Virginia             1209.8240
North Dakota               919.9100
Name: Sales, dtype: float64

Sales by region

In [ ]:
sales_by_region = df.groupby('Region')['Sales'].sum().sort_values(ascending=False)
sales_by_region

Region
West       710219.6845
East       669518.7260
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

# 3.Shipping Performance Analysis

 Average Delivery Duration

In [ ]:
#change datatype
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)

df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

#Calculate delivery duration
df['Delivery Duration'] = df['Ship Date'] - df['Order Date']

#Average
Average_delivery_duration = df['Delivery Duration'].mean()
Average_delivery_duration

Timedelta('3 days 23:04:00.979591836')

Shipping Mode Performance

In [ ]:
shipping_stats = df.groupby('Ship Mode').agg({
    'Delivery Duration': 'mean',
    'Order ID': 'count',
    'Sales': 'sum'
}).rename(columns={
    'Delivery Duration': 'AVG Delivery Duration',
    'Order ID': 'Total Orders',
    'Sales': 'Total Sales'
}).sort_values(by='Total Sales', ascending=False)

shipping_stats

                   AVG Delivery Duration  Total Orders   Total Sales
Ship Mode
Standard Class 5 days 00:12:02.580645161          5859  1.340831e+06
Second Class   3 days 05:58:51.861198738          1902  4.499142e+05
First Class    2 days 04:18:04.077281812          1501  3.455723e+05
Same Day       0 days 01:04:14.275092936           538  1.252190e+05

# 4.The relationship between category and sales

Sales By Category

In [ ]:
Sales_by_category = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)
Sales_by_category

Category
Technology         827455.8730
Furniture          728658.5757
Office Supplies    705422.3340
Name: Sales, dtype: float64